POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "https://mrmrs.cc/writing/design-reading",
  "author": "Adam Morse",
  "url": "https://mrmrs.cc/writing/design-reading",
  "likes": 0
}

###
GET http://localhost:3003/api/blogs

###
DELETE http://localhost:3003/api/blogs/60a241784e7c82223038049f